import enum
from datetime import datetime
from typing import Optional, Literal, List, Dict
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import Column, Integer, String, Text, ForeignKey, Boolean, DateTime, Enum, JSON
from app.db.db import Base

# ==========================================
# 1. ENUMS & CORE WORKFLOW STATES
# ==========================================
class WorkflowStatusEnum(str, enum.Enum):
    DRAFTED = "drafted"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"


# ==========================================
# 2. PYDANTIC SCHEMAS (Request/Response Validation)
# ==========================================

# --- User / Patient Schemas ---
class UserBase(BaseModel):
    username: str
    email: EmailStr

class UserCreate(UserBase):
    password: str

class UserResponse(UserBase):
    id: int
    is_active: bool

    model_config = {
        "from_attributes": True  # Standardized to Pydantic v2
    }

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    username: Optional[str] = None


# --- AI Engine Extractor & Payload Schemas ---
class DemographicsExtractor(BaseModel):
    age: Optional[int] = Field(None, description="Age in years")
    gender: Optional[str] = Field(None, description="Biological sex")
    weight: Optional[str] = Field(None, description="Weight with units if provided")
    height: Optional[str] = Field(None, description="Height with units if provided")
    previous_diseases: Optional[str] = Field(None, description="Any pre-existing conditions, chronic illnesses, or past surgeries mentioned by the user.")
    all_collected: bool = Field(..., description="True only if age, gender, weight, height, AND previous diseases are successfully extracted.")

class MedicalReport(BaseModel):
    triage_urgency: Literal["EMERGENCY", "SCHEDULE_DOCTOR", "SELF_CARE"]
    probable_conditions: List[Dict[str, str]] = Field(..., description="Keys: condition_name, likelihood, explanation")
    recommended_tests: List[Dict[str, str]] = Field(..., description="Keys: test_name, purpose")
    precautions: List[str]

class ChatMessage(BaseModel):
    role: Literal["user", "assistant"] = "user"
    content: str

class MedicalChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000)
    language: str = "English"
    context: Optional[str] = None
    history: List[ChatMessage] = Field(default_factory=list)

class MedicalChatResponse(BaseModel):
    reply: str


# --- Doctor Schemas ---
class DoctorCreate(BaseModel):
    name: str = Field(..., min_length=2, max_length=100, description="Full professional name of the medical practitioner")
    email: EmailStr = Field(..., description="Verified institutional or clinical email address")
    password: str = Field(..., min_length=8, max_length=64, description="Secure password, must contain at least 8 characters")

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Dr. Sarah Jenkins",
                "email": "dr.jenkins@hospital.org",
                "password": "SuperSecurePassword123!"
            }
        }
    }

class DoctorResponse(BaseModel):
    id: int
    name: str
    email: EmailStr
    is_active: bool

    model_config = {
        "from_attributes": True
    }


# --- Dynamic Prescription Workflow Schemas ---
class WorkflowSubmit(BaseModel):
    doctor_email: EmailStr = Field(..., description="The target doctor's email where the patient wants to route their report")
    ai_response_text: str = Field(..., min_length=10, description="The raw stringified disease list and medical summary generated by your RAG/LLM engine")
    patient_language: str = Field("English", description="Patient selected consultation language")
    uploaded_filename: Optional[str] = Field(None, description="Original PDF filename, when available")

    model_config = {
        "json_schema_extra": {
            "example": {
                "doctor_email": "dr.jenkins@hospital.org",
                "ai_response_text": "EXPLICIT DISEASE & CONDITION ANALYSIS:\n1. Identified Diseases:\n- Diabetes Mellitus\n- Combined Dyslipidemia"
            }
        }
    }

class MedicationItem(BaseModel):
    drug_name: str = ""
    dosage: str = ""
    frequency: str = ""
    duration: str = ""

class PrescriptionUpdate(BaseModel):
    medications: List[MedicationItem] = Field(default_factory=list)
    remarks: str = ""

class PrescriptionApproval(PrescriptionUpdate):
    model_config = {
        "json_schema_extra": {
            "example": {
                "medications": [
                    {
                        "drug_name": "Metformin",
                        "dosage": "500mg",
                        "frequency": "Twice daily",
                        "duration": "30 days"
                    }
                ],
                "remarks": "Review glucose profile after 2 weeks."
            }
        }
    }

class WorkflowDetailResponse(BaseModel):
    id: int
    user_id: int
    doctor_id: int
    ai_generated_draft: str
    patient_language: str = "English"
    uploaded_filename: Optional[str] = None
    prescription_data: Optional[List[MedicationItem]] = None
    clinical_remarks: Optional[str] = None
    final_prescription: Optional[str] = None
    status: WorkflowStatusEnum
    created_at: datetime
    updated_at: datetime
    approved_at: Optional[datetime] = None

    model_config = {
        "from_attributes": True
    }


# ==========================================
# 3. SQLALCHEMY MODELS (Database Persistent Tables)
# ==========================================
class DoctorModel(Base):
    __tablename__ = "doctors"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    is_active = Column(Boolean, default=True)


class PrescriptionWorkflow(Base):
    __tablename__ = "prescription_workflows"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    doctor_id = Column(Integer, ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False)
    
    # Clinical Artifact Storage
    ai_generated_draft = Column(Text, nullable=False)
    patient_language = Column(String(32), nullable=False, default="English")
    uploaded_filename = Column(String(255), nullable=True)
    prescription_data = Column(JSON, nullable=True, default=list)
    clinical_remarks = Column(Text, nullable=True)
    final_prescription = Column(Text, nullable=True)
    
    status = Column(
        Enum(WorkflowStatusEnum, values_callable=lambda values: [item.value for item in values]),
        default=WorkflowStatusEnum.DRAFTED,
        index=True
    )
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    approved_at = Column(DateTime, nullable=True)
    
