import enum
from datetime import datetime
from typing import Optional, Literal, List, Dict
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import Column, Integer, String, Text, ForeignKey, Boolean, DateTime, Enum
from app.db.db import Base

# ==========================================
# 1. ENUMS & CORE WORKFLOW STATES
# ==========================================
class WorkflowStatusEnum(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"


# ==========================================
# 2. PYDANTIC SCHEMAS (Request/Response Validation)
# ==========================================

# --- User / Patient Schemas ---
class UserBase(BaseModel):
    username: str
    email: EmailStr

class UserCreate(UserBase):
    password: str

class UserResponse(UserBase):
    id: int
    is_active: bool

    model_config = {
        "from_attributes": True  # Standardized to Pydantic v2
    }

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    username: Optional[str] = None


# --- AI Engine Extractor & Payload Schemas ---
class DemographicsExtractor(BaseModel):
    age: Optional[int] = Field(None, description="Age in years")
    gender: Optional[str] = Field(None, description="Biological sex")
    weight: Optional[str] = Field(None, description="Weight with units if provided")
    height: Optional[str] = Field(None, description="Height with units if provided")
    previous_diseases: Optional[str] = Field(None, description="Any pre-existing conditions, chronic illnesses, or past surgeries mentioned by the user.")
    all_collected: bool = Field(..., description="True only if age, gender, weight, height, AND previous diseases are successfully extracted.")

class MedicalReport(BaseModel):
    triage_urgency: Literal["EMERGENCY", "SCHEDULE_DOCTOR", "SELF_CARE"]
    probable_conditions: List[Dict[str, str]] = Field(..., description="Keys: condition_name, likelihood, explanation")
    recommended_tests: List[Dict[str, str]] = Field(..., description="Keys: test_name, purpose")
    precautions: List[str]

class ChatPayload(BaseModel):
    current_stage: Literal["DEMOGRAPHICS", "INTAKE", "FOLLOW_UP", "FINAL"] = "DEMOGRAPHICS"
    language: str = "English"
    demographics: Dict[str, Optional[str]] = {
        "age": None, 
        "gender": None, 
        "weight": None, 
        "height": None,
        "previous_diseases": None
    }
    raw_symptoms: str = ""
    follow_up_count: int = 0
    chat_history: List[Dict[str, str]] = []
    final_output: Optional[Dict] = None


# --- Doctor Schemas ---
class DoctorCreate(BaseModel):
    name: str = Field(..., min_length=2, max_length=100, description="Full professional name of the medical practitioner")
    email: EmailStr = Field(..., description="Verified institutional or clinical email address")
    password: str = Field(..., min_length=8, max_length=64, description="Secure password, must contain at least 8 characters")

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Dr. Sarah Jenkins",
                "email": "dr.jenkins@hospital.org",
                "password": "SuperSecurePassword123!"
            }
        }
    }

class DoctorResponse(BaseModel):
    id: int
    name: str
    email: EmailStr
    is_active: bool

    model_config = {
        "from_attributes": True
    }


# --- Dynamic Prescription Workflow Schemas ---
class WorkflowSubmit(BaseModel):
    doctor_email: EmailStr = Field(..., description="The target doctor's email where the patient wants to route their report")
    ai_response_text: str = Field(..., min_length=10, description="The raw stringified disease list and medical summary generated by your RAG/LLM engine")

    model_config = {
        "json_schema_extra": {
            "example": {
                "doctor_email": "dr.jenkins@hospital.org",
                "ai_response_text": "EXPLICIT DISEASE & CONDITION ANALYSIS:\n1. Identified Diseases:\n- Diabetes Mellitus\n- Combined Dyslipidemia"
            }
        }
    }

class PrescriptionApproval(BaseModel):
    workflow_id: int = Field(..., description="The unique database tracking primary key ID of the target pending interaction row")
    doctor_edited_medications: str = Field(..., min_length=10, description="The final medical directives explicitly modified, reviewed, and authorized by the physician")

    model_config = {
        "json_schema_extra": {
            "example": {
                "workflow_id": 42,
                "doctor_edited_medications": "Metformin 500mg - Take 1 tablet orally twice daily with meals.\nAtorvastatin 20mg - Take 1 tablet orally at bedtime daily."
            }
        }
    }

class WorkflowDetailResponse(BaseModel):
    id: int
    user_id: int
    doctor_id: int
    ai_generated_draft: str
    final_prescription: Optional[str] = None
    status: WorkflowStatusEnum
    created_at: datetime
    updated_at: datetime

    model_config = {
        "from_attributes": True
    }


# ==========================================
# 3. SQLALCHEMY MODELS (Database Persistent Tables)
# ==========================================
class DoctorModel(Base):
    __tablename__ = "doctors"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    is_active = Column(Boolean, default=True)


class PrescriptionWorkflow(Base):
    __tablename__ = "prescription_workflows"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    doctor_id = Column(Integer, ForeignKey("doctors.id", ondelete="CASCADE"), nullable=False)
    
    # Clinical Artifact Storage
    ai_generated_draft = Column(Text, nullable=False)
    final_prescription = Column(Text, nullable=True)
    
    status = Column(Enum(WorkflowStatusEnum), default=WorkflowStatusEnum.PENDING, index=True)
    created_at = Column(DateTime, default=datetime) # ◄--- FIX: Changed from datetime to datetime.utcnow
    updated_at = Column(DateTime, default=datetime, onupdate=datetime) # ◄--- FIX: Changed from datetime to datetime.utcnow
    
